version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "rz-stack-lambda"
s3_bucket = "rz-ds-resources"
s3_prefix = "rz-stack-lambda"
region = "eu-west-1"
profile = "rz-robot"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
